config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "aquarium_discoveries#index"
  resources :animals do
    resources :comments
    collection do
      get 'search'
    end
  end
  resources :aquariums do
    resources :reviews
    collection do
      get 'search'
    end
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many :animal_aquariums
  has_many :aquarium, through: :animal_aquariums
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  def self.search(search)
    if search != ""
      Animal.where('name LIKE(?)', "%#{search}%")
    else
      Animal.all
    end
  end

  validates :category_id, numericality: { other_than: 1 , message: "は選択必須です"}
end

app/models/animal_aquarium.rb
class AnimalAquarium < ApplicationRecord
  belongs_to :animal
  belongs_to :aquarium
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aquarium.rb
class Aquarium < ApplicationRecord
  has_many :animals, through: :animal_aquariums
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :area

  def self.search(search)
    if search != ""
      Aquarium.where('name LIKE(?)', "%#{search}%")
    else
      Aquarium.all
    end
  end

  validates :area_id, numericality: { other_than: 1 , message: "は選択必須です"}
end

app/models/area.rb
class Area < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '北海道' },
    { id: 3, name: '東北' },
    { id: 4, name: '関東' },
    { id: 5, name: '中部' },
    { id: 6, name: '近畿' },
    { id: 7, name: '中国、四国' },
    { id: 8, name: '九州' },
    { id: 9, name: '沖縄' },
    { id: 10, name: 'その他' },
  ]

  include ActiveHash::Associations
  has_many :aquariums
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: 'イルカ' },
    { id: 3, name: 'サメ' },
    { id: 4, name: 'カメ' },
    { id: 5, name: 'カニ' },
    { id: 6, name: 'エビ' },
    { id: 7, name: 'イカ' },
    { id: 8, name: 'タコ' },
    { id: 9, name: 'ヒトデ' },
    { id: 10, name: 'エイ' },
    { id: 11, name: 'ペンギン' },
    { id: 12, name: 'クラゲ' },
  ]

  include ActiveHash::Associations
  has_many :animals
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_many :comments
  # has_many :reviews
  # has_many :animals
  # has_many :aquariums

  validates :name,     presence: true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :authenticate_user!, only: [:new,:edit]
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  def index
    @animals =Animal.search(params[:keyword])
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      redirect_to root_path
    else
      render :new
    end

  end

  def show
  end

  def edit
  end

  def update
    if @animal.update(animal_params)
      redirect_to animal_path
    else
      render :edit
    end
  end

  def destroy
    @animal.destroy
    redirect_to root_path
  end

  def search
  end

  private

  def animal_params
    params.require(:animal).permit(
      :name, :detail, :category_id, :image,
    ).merge(aquarium_ids: params[:aquarium_ids])
  end

  def set_animal
    @animal = Animal.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/aquarium_discoveries_controller.rb
class AquariumDiscoveriesController < ApplicationController

  def index
  end
  
end

app/controllers/aquariums_controller.rb
class AquariumsController < ApplicationController
  before_action :authenticate_user!, only: [:new,:edit]
  before_action :set_aquarium, only: [:show, :edit, :update, :destroy]
  def index
    @aquariums =Aquarium.search(params[:keyword])
  end

  def new
    @aquarium = Aquarium.new
  end

  def create
    @aquarium = Aquarium.new(aquarium_params)
    if @aquarium.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @aquarium.update(aquarium_params)
      redirect_to aquarium_path
    else
      render :edit
    end
  end

  def destroy
    @aquarium.destroy
    redirect_to root_path
  end

  def search
  end

  private

  def aquarium_params
    params.require(:aquarium).permit(
      :name, :detail, :area_id, :image
    )
  end

  def set_aquarium
    @aquarium = Aquarium.find(params[:id])
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aquarium_discoveries_helper.rb
module AquariumDiscoveriesHelper
end

app/helpers/aquariums_helper.rb
module AquariumsHelper
end

app/views/animals/_animal.html.erb
<div class='whole' >
  <ul class='animal-list'>
    <%= link_to animal_path(animal.id) do %>
    <li>
      <%= animal.name %>
    </li>
    <li>
      <%= animal.category.name %>
    </li>
    <li>
      <%= image_tag animal.image, class:"animal-image" %>
    </li>
    <% end %>
  </ul>
</div>

app/views/animals/edit.html.erb
<h1>Animals#edit</h1>
<div class="whole">
  <div class="animals-post-main">
    <h2 class="animals-post-title">生き物の情報を入力</h2>
    <%= form_with model: @animal, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <%# 生き物情報 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        生き物の画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"animal-image" %>
      </div>
    </div>
    <div class="new-animals">
      <div class="weight-bold-text">
        生き物の名前
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"animals-text", id:"animal-name", placeholder:"生き物名" %>
      <div class="animals-explain">
        <div class="weight-bold-text">
          生き物の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :detail, class:"animals-text", id:"animal-info", placeholder:"生き物の説明（必須 1,500文字まで）" ,rows:"15" ,maxlength:"1500" %>
      </div>
    </div>
    <div class="animals-detail">
      <div class="weight-bold-text">生き物の関連情報</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"animal-category"}) %>
        <div class="weight-bold-text">
          展示されている水族館
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_check_boxes(:aquarium_ids, Aquarium.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"displayed-aquarium"}) %>
      </div>
    </div>
    <div class="post-btn-contents">
      <%= f.submit "投稿する" ,class:"post-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <% end %>


  </div>
</div>

app/views/animals/index.html.erb
<%= render "shared/header" %>
<h1>Animals#index</h1>
<div class='search-index'>
  <% @animals.each do |animal| %>
    <%= render partial: "animal", locals: { animal: animal } %>
  <% end %>
</div>

app/views/animals/new.html.erb
<div class="whole">
  <div class="animals-post-main">
    <h2 class="animals-post-title">生き物の情報を入力</h2>
    <%= form_with model: @animal, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <%# 生き物情報 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        生き物の画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"animal-image" %>
      </div>
    </div>
    <div class="new-animals">
      <div class="weight-bold-text">
        生き物の名前
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"animals-text", id:"animal-name", placeholder:"生き物名" %>
      <div class="animals-explain">
        <div class="weight-bold-text">
          生き物の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :detail, class:"animals-text", id:"animal-info", placeholder:"生き物の説明（必須 1,500文字まで）" ,rows:"15" ,maxlength:"1500" %>
      </div>
    </div>
    <div class="animals-detail">
      <div class="weight-bold-text">生き物の関連情報</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"animal-category"}) %>
        <div class="weight-bold-text">
          展示されている水族館
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_check_boxes(:aquarium_ids, Aquarium.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"displayed-aquarium"}) %>
      </div>
    </div>
    <div class="post-btn-contents">
      <%= f.submit "投稿する" ,class:"post-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <% end %>


  </div>
</div>

app/views/animals/search.html.erb
<h1>Animals#search</h1>
<p>Find me in app/views/animals/search.html.erb</p>

<div class='search-form'>
<%= form_with(url: animals_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
</div>

app/views/animals/show.html.erb
<%= render "shared/header" %>
<h1>Animals#show</h1>
<div class="animal-show">
  <div class="animal-box">
    <h2 class="name">
      <%= @animal.name %>
    </h2>
    <div class="animal-img-content">
      <%= image_tag @animal.image, class:"animal-box-img" %>
    </div>
    <div class="animal-category-box">
      カテゴリー:
      <%= @animal.category.name %>
    </div>
    <div class="animal-explain-box">
      <span><%= @animal.detail %></span>
    </div>
    <% if user_signed_in? && current_user.id == 1 %>
    <%= link_to "情報編集", edit_animal_path, method: :get, class: "animal-red-btn" %>
    <p class="or-text">or</p>
    <%= link_to "情報削除", animal_path, method: :delete, class:"animal-destroy" %>
    <% end %>
  </div>
</div>

app/views/aquarium_discoveries/index.html.erb
<%= render "shared/header" %>
<div class='main'>
  <div class='title'>
    <div class='title-contents'>
      <h2 class='servise-explain1'>
        水族館を探そう！生き物を見つけよう！
      </h2>
      <p class='servise-explain2'>
        好きな方を選んで検索してね
      </p>
    </div>
  </div>

  <div class="links-for-viewer">
    <div class="links-to-search">
      <%= link_to "生き物検索", search_animals_path, class: "link-to-animal-search" %>
      <%= link_to "水族館検索", search_aquariums_path, class: "link-to-aquarium-search" %>
    </div>
  </div>

  <div class="links-for-admin">
    <div class="links-to-post">
      <%= link_to "（管理所用リンク）生き物投稿", new_animal_path, class: "link-to-post" %>
      <%= link_to "（管理所用リンク）水族館投稿", new_aquarium_path, class: "link-to-post" %>
    </div>
  </div>
</div>

app/views/aquariums/_aquarium.html.erb
<div class='whole'>
  <ul class='aquarium-list'>
    <%= link_to aquarium_path(aquarium.id) do %>
    <li>
      <%= aquarium.name %>
    </li>
    <li>
      <%= aquarium.area.name %>
    </li>
    <li>
      <%= image_tag aquarium.image, class:"aquarium-image" %>
    </li>
    <% end %>
  </ul>
</div>

app/views/aquariums/edit.html.erb
<h1>Aquariums#edit</h1>
<div class="whole">
  <div class="aquariums-post-main">
    <h2 class="aquariums-post-title">水族館の情報を入力</h2>
    <%= form_with url: aquarium_path, model: @aquarium, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <%# 水族館情報 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        水族館の画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"aqurium-image" %>
      </div>
    </div>
    <div class="new-aquriums">
      <div class="weight-bold-text">
        水族館名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"aquariums-text", id:"aquarium-name", placeholder:"水族館名" %>
      <div class="aquariums-explain">
        <div class="weight-bold-text">
          水族館の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :detail, class:"aquariums-text", id:"aquarium-info", placeholder:"水族館の説明（必須 1,500文字まで）" ,rows:"15" ,maxlength:"1500" %>
      </div>
    </div>
    <div class="aquariums-detail">
      <div class="weight-bold-text">水族館の関連情報</div>
      <div class="form">
        <div class="weight-bold-text">
          地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"aquarium-area"}) %>
      </div>
    </div>
    <div class="post-btn-contents">
      <%= f.submit "投稿する" ,class:"post-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <% end %>


  </div>
</div>

app/views/aquariums/index.html.erb
<%= render "shared/header" %>
<div class='search-index'>
  <% @aquariums.each do |aquarium| %>
    <%= render partial: "aquarium", locals: { aquarium: aquarium } %>
  <% end %>
</div>

app/views/aquariums/new.html.erb
<h1>Aquariums#new</h1>
<div class="whole">
  <div class="aquariums-post-main">
    <h2 class="aquariums-post-title">水族館の情報を入力</h2>
    <%= form_with url: aquariums_path, model: @aquarium, local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>

    <%# 水族館情報 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        水族館の画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"aqurium-image" %>
      </div>
    </div>
    <div class="new-aquriums">
      <div class="weight-bold-text">
        水族館名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"aquariums-text", id:"aquarium-name", placeholder:"水族館名" %>
      <div class="aquariums-explain">
        <div class="weight-bold-text">
          水族館の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :detail, class:"aquariums-text", id:"aquarium-info", placeholder:"水族館の説明（必須 1,500文字まで）" ,rows:"15" ,maxlength:"1500" %>
      </div>
    </div>
    <div class="aquariums-detail">
      <div class="weight-bold-text">水族館の関連情報</div>
      <div class="form">
        <div class="weight-bold-text">
          地域
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"select-box", id:"aquarium-area"}) %>
      </div>
    </div>
    <div class="post-btn-contents">
      <%= f.submit "投稿する" ,class:"post-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <% end %>


  </div>
</div>

app/views/aquariums/search.html.erb
<h1>Aquariums#search</h1>
<p>Find me in app/views/aquariums/search.html.erb</p>

<div class='search-form'>
<%= form_with(url: aquariums_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
</div>

app/views/aquariums/show.html.erb
<%= render "shared/header" %>
<h1>Aquariums#show</h1>
<div class="aquarium-show">
  <div class="aquarium-box">
    <h2 class="name">
      <%= @aquarium.name %>
    </h2>
    <div class="aquarium-img-content">
      <%= image_tag @aquarium.image, class:"animal-box-img" %>
    </div>
    <div class="aquarium-area-box">
      カテゴリー:
      <%= @aquarium.area.name %>
    </div>
    <div class="aquarium-explain-box">
      <span><%= @aquarium.detail %></span>
    </div>
    <% if user_signed_in? && current_user.id == 1 %>
    <%= link_to "情報編集", edit_aquarium_path, method: :get, class: "aquarium-red-btn" %>
    <p class="or-text">or</p>
    <%= link_to "情報削除", aquarium_path, method: :delete, class:"aquarium-destroy" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AquariumDiscovery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='top-page-link'>
  <%= link_to 'AquariumDiscovery', '/', class: "top-page-text" %>
  </div>
  <div class='nav'>
  <ul class='user-lists'>
      <% if user_signed_in? %> 
      <li><%= link_to current_user.name, "#", class: "user-nickname" %> </li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %> </li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>